### ISSUE TITLE
Smittestopp requires location services to be turned on (Android 11)

### ISSUE THREAD

**Issue by huaracheguarache** [folkehelseinstituttet/Fhi.Smittestopp.App#268]
The latest version of Smittestopp requires that location services must be enabled on Android 11 for it to work. This is only needed on Android 10 and earlier versions. I get the following warning on my Samsung Galaxy S20 FE:

![ss1](https://user-images.githubusercontent.com/33153877/105250502-2a5fef00-5b7a-11eb-99e0-d98c1ffdfeab.jpeg)

This is the latest version as can be seen here:

![ss2](https://user-images.githubusercontent.com/33153877/105250536-39df3800-5b7a-11eb-828f-cc9fdd3371ed.jpeg)

**Comment by CUSL78** [comment]
@jonasofrich Hi can you report this in Azure Devops as a bug as well so that we have it ready for the testers?

**Comment by jonasofrich** [comment]
@CUSL78 Yes, this is the same issue. I updated the name in Devops to better reflect that

**Comment by Frederik-S-N-dk** [comment]
This is being handled as a bug by the app development team.
Resolving the bug is in progress.

**Comment by jonasofrich** [comment]
This issue is resolved in #269, where we now bypass the location service check for Android versions from 11 (API 30) and up.  A new version is submitted to Google for review under the same version name (1.0.2) but with build version 12, and will be published to Google Play ASAP.

Bringing this to our attention also allowed us to resolve #222

@huaracheguarache 
Thank you for reporting this issue, and allowing us to fix this so quickly!
