### ISSUE TITLE
Users will not receive notifications unless their phone is connected to data at 7am

### ISSUE THREAD

**Issue by MgtPa** [folkehelseinstituttet/Fhi.Smittestopp.App#447]
Observed on my Huawei Mate 10 Pro with EMUI 10.0.0, Android 10, Smittestopp app v2.1.

Issue description:
---
On March 13th, in the "Meldinger" section of the app the information,"sist oppdatert 17.Februar kl 07.01" was visible despite regular (almost daily) use of Smittestopp app. 
Looking at data usage over the past 30 days, there was very minor data usage until Feb 16th, a "peak" at 1.64Mo on Feb 17th and then 0.00o until March 13th. 

In order to protect my battery, I usually turn off Smittestopp when I am at home (no need to probe my surroundings then) and turn it on when I get outside. Additionally, I put my phone in Flight Mode during the night, no sim card action nor wifi nor bluetooth. 

Test
---
After having read that Smittestopp only updates the messages section once a day, I ran a small experiment and left wifi, bluetooth and Smittestopp on during the night and today the Meldinger session had "Sist oppdatert 14.mars kl07.01".

Consequences for user
---
I was very happy to be using the app, both to be able to warn people if I test positive and to be warned. It seems that because I do not wake up before 7am (and thus don't turn on my phone before that time), I would not have been  notified for any close contact between Feb 17th and today. 

Conclusion
---
It seems problematic for the system to expect of its users to have both the app open and network access at 7am everyday to be notified. I understand the choice to do only one notification check/push per day, but having it at a fixed time with no retries does not seem optimal (and was worrying for me). 

It would be great to have a force refresh possibility ("check for messages" button inside the Meldinger section) for example.
For me, it would probably be enough that the app checks when I turn it on when getting outside, but for users that only do the other part (having their phone off grid at 7am but not switching off the app), then it wouldn't be enough.

**Comment by pavshr** [comment]
Hello @MgtPa and thank you for reporting the issue.

There is some information we first want to clarify first. The app itself does not use any specific time of the day to schedule running of the background task at. What the app does, it that it schedules the background task to fetch the keys and perform analysis of the given keys periodically with at least 4 hour intervals. So the initial scheduling and approximate time of the background task's execution is rather dependent on when you originally install and activate the app than any specific time of the day. Of course, some other factors play an important role here. For instance, if you disable the app (disable it from using EN API on your phone, or turn off Bluetooth), then the analysis is not possible at all because the app is no longer authorized to make calls to EN API. In order to stay updated, Smittestopp has to be active (green/ON status on the main page). 

Furthermore, fetching of the keys might fail at any point after it has started due to network errors and timeouts, running out of battery or other external and internal factors. An expected behavior in such cases is to retry at some point later (in ca. 4 hours). But in this case, the label with the date in the Messages view should be updated, indicating that an attempt to run a task has been made.

The fact that the label in the Messages view is not updated for a while for you, indicates that the app at some point stopped to run background task at all. Most likely, it happens due to battery optimizations that different OEMs implement in their firmware. If you think in general, Smittestopp is installed on a device, activated, and then left in the background until user receives an Exposure Notification or needs to report infected. The users are not expected to open the app regularly. And from OS perspective, it seems that the app is not used/opened, thus, less and less resources are allocated to the app in the background and in the end it ends up functioning.

It is a known issue for us and Google, and we work constantly on debugging and addressing it. Thanks again for reporting this one, I guess we would have to run some tests on Huawei/EMUI devices by ourselves. As a temporary workaround, you can do some whitelisting from battery optimizations on your device by yourself (see [https://dontkillmyapp.com/huawei](https://dontkillmyapp.com/huawei)). Let us know if this will give you better results in terms of whether the task periodically runs in background or not.

**Comment by MgtPa** [comment]
Thank you @pavshr for the reply. Coincidentally, I had run the same test two nights ago, and I could see that my analysis was not correct. 
I will try the whitelisting, as I really want to be warned if I get in contact with someone contaminated. 
How about forcing the refresh through a button in the "Meldinger" section though? It would be great for a user's peace of mind I think. 
Anyhow, thank you for your reply.

**Comment by Michael-Olesen** [comment]
@MgtPa With the release of version 3.1 of the Smittestopp App yesterday, the app now fetches keys when it is opened on Android.
